<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a4b0a8eb-ef9a-454f-b01c-9932f398fe96</testSuiteGuid>
   <testCaseLink>
      <guid>8b6e8865-36f6-4754-aecb-fb11d97ff0a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f8af7a82-49d1-460b-bbfe-433c600d6501</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f8af7a82-49d1-460b-bbfe-433c600d6501</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>25da97a6-bac1-4ccd-84d8-b24b0c272f6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8af7a82-49d1-460b-bbfe-433c600d6501</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>62cc47bd-967f-4220-b139-e00a372b404a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
